#!/bin/bash
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '0;0;0' -init_stdev 0.1 -out ./Result/1
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '0;0;2' -init_stdev 0.1 -out ./Result/2
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '0;0;4' -init_stdev 0.1 -out ./Result/3
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '0;0;8' -init_stdev 0.1 -out ./Result/4
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '0;0;16' -init_stdev 0.1 -out ./Result/5
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '0;0;24' -init_stdev 0.1 -out ./Result/6
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '0;0;32' -init_stdev 0.1 -out ./Result/7
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '0;0;40' -init_stdev 0.1 -out ./Result/8
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '1;0;0' -init_stdev 0.1 -out ./Result/9
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '1;0;2' -init_stdev 0.1 -out ./Result/10
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '1;0;4' -init_stdev 0.1 -out ./Result/11
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '1;0;8' -init_stdev 0.1 -out ./Result/12
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '1;0;16' -init_stdev 0.1 -out ./Result/13
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '1;0;24' -init_stdev 0.1 -out ./Result/14
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '1;0;32' -init_stdev 0.1 -out ./Result/15
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '1;0;40' -init_stdev 0.1 -out ./Result/16
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '1;1;0' -init_stdev 0.1 -out ./Result/17
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '1;1;2' -init_stdev 0.1 -out ./Result/18
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '1;1;4' -init_stdev 0.1 -out ./Result/19
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '1;1;8' -init_stdev 0.1 -out ./Result/20
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '1;1;16' -init_stdev 0.1 -out ./Result/21
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '1;1;24' -init_stdev 0.1 -out ./Result/22
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '1;1;32' -init_stdev 0.1 -out ./Result/23
./bin/libFM -task c -train ./app_train_mat.pkl -test ./app_train_mat.pkl  -iter 50 -dim '1;1;40' -init_stdev 0.1 -out ./Result/24
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '0;0;0' -init_stdev 0.1 -out ./Result/001
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '0;0;2' -init_stdev 0.1 -out ./Result/002
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '0;0;4' -init_stdev 0.1 -out ./Result/003
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '0;0;8' -init_stdev 0.1 -out ./Result/004
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '0;0;16' -init_stdev 0.1 -out ./Result/005
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '0;0;24' -init_stdev 0.1 -out ./Result/006
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '0;0;32' -init_stdev 0.1 -out ./Result/007
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '0;0;40' -init_stdev 0.1 -out ./Result/008
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '1;0;0' -init_stdev 0.1 -out ./Result/009
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '1;0;2' -init_stdev 0.1 -out ./Result/0010
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '1;0;4' -init_stdev 0.1 -out ./Result/0011
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '1;0;8' -init_stdev 0.1 -out ./Result/0012
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '1;0;16' -init_stdev 0.1 -out ./Result/0013
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '1;0;24' -init_stdev 0.1 -out ./Result/0014
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '1;0;32' -init_stdev 0.1 -out ./Result/0015
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '1;0;40' -init_stdev 0.1 -out ./Result/0016
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '1;1;0' -init_stdev 0.1 -out ./Result/0017
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '1;1;2' -init_stdev 0.1 -out ./Result/0018
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '1;1;4' -init_stdev 0.1 -out ./Result/0019
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '1;1;8' -init_stdev 0.1 -out ./Result/0020
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '1;1;16' -init_stdev 0.1 -out ./Result/0021
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '1;1;24' -init_stdev 0.1 -out ./Result/0022
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '1;1;32' -init_stdev 0.1 -out ./Result/0023
./bin/libFM -task c -train ./app_train_mat.pkl -test ./article_test_mat.pkl  -iter 50 -dim '1;1;40' -init_stdev 0.1 -out ./Result/0024